/* Leadlight's glass, as data. GENERATED by scripts/leadlight-art.mjs from
   LeadlightRN itself — do not edit by hand; re-run the script instead.

   - PANES and PALETTES are the game's own: src/core/config.js (PANES, PANE_NAMES)
     and src/ui/palette.js, with the unlock rules from src/core/profile.js.
   - ICON is demoWindow({ pane: 'lancet', cuts: 7, seed: 11, clear: 1 }) from
     src/core/demo.js — the window tools/make-icons.py draws the app icon from —
     with its one spark at the clear shard's centre, as the icon has it.
   - SCENE is a late-game board cut with the game's own split() and coloured by
     demo.js's rule (seed 2): one clear piece still holding three sparks, and
     a cut across it that seals the spark-free half. Every piece is convex, as
     every piece in the game is.

   Coordinates are the game's world, 360 x 600. */

export const WORLD = { width: 360, height: 600 };

export const PANES = [
  { id: 'tall', name: 'Tall light', pts: [16, 584, 16, 16, 344, 16, 344, 584] },
  { id: 'arch', name: 'Round arch', pts: [16, 584, 16, 180, 19.2, 148, 28.5, 117.2, 43.6, 88.9, 64, 64, 88.9, 43.6, 117.2, 28.5, 148, 19.2, 180, 16, 212, 19.2, 242.8, 28.5, 271.1, 43.6, 296, 64, 316.4, 88.9, 331.5, 117.2, 340.9, 148, 344, 180, 344, 584] },
  { id: 'lancet', name: 'Lancet', pts: [16, 584, 16, 300.1, 17.8, 265.8, 23.2, 231.9, 32.1, 198.7, 44.4, 166.7, 59.9, 136.1, 78.6, 107.3, 100.3, 80.6, 124.5, 56.3, 151.2, 34.7, 180, 16, 208.8, 34.7, 235.5, 56.3, 259.8, 80.6, 281.4, 107.3, 300.1, 136.1, 315.6, 166.7, 328, 198.7, 336.8, 231.9, 342.2, 265.8, 344, 300.1, 344, 584] },
  { id: 'hexagon', name: 'Hexagon', pts: [16, 140, 180, 16, 344, 140, 344, 460, 180, 584, 16, 460] },
  { id: 'octagon', name: 'Octagon', pts: [16, 518, 16, 82, 82, 16, 278, 16, 344, 82, 344, 518, 278, 584, 82, 584] },
  { id: 'rose', name: 'Rose window', pts: [19.2, 268, 28.5, 237.2, 43.6, 208.9, 64, 184, 88.9, 163.6, 117.2, 148.5, 148, 139.2, 180, 136, 212, 139.2, 242.8, 148.5, 271.1, 163.6, 296, 184, 316.4, 208.9, 331.5, 237.2, 340.9, 268, 344, 300, 340.9, 332, 331.5, 362.8, 316.4, 391.1, 296, 416, 271.1, 436.4, 242.8, 451.5, 212, 460.9, 180, 464, 148, 460.9, 117.2, 451.5, 88.9, 436.4, 64, 416, 43.6, 391.1, 28.5, 362.8, 19.2, 332, 16, 300] },
];

export const PALETTES = [
  { id: 'cathedral', name: 'Cathedral', need: null, glass: ['#c0283a', '#2458c4', '#1f9153', '#eaa220', '#7a3fb0', '#dd6a3a'],
    clear: '#9fb4c8', lead: '#17120e', leadHi: '#5d5046', frame: '#2c2219', light: '#fff1cf' },
  { id: 'tiffany', name: 'Tiffany', need: { windows: 8 }, glass: ['#3aae95', '#ecb450', '#6cb8e0', '#e98aa6', '#86b54f', '#a88ddc'],
    clear: '#c9d6c4', lead: '#1c1712', leadHi: '#6a5b49', frame: '#34291c', light: '#fff6dc' },
  { id: 'deco', name: 'Art Deco', need: { windows: 25 }, glass: ['#d9a93c', '#1d7f8a', '#e0715c', '#efe0bd', '#4f9e7a', '#303a52'],
    clear: '#b6b4a6', lead: '#121212', leadHi: '#8a7a55', frame: '#1e1c1a', light: '#fff3d6' },
  { id: 'mondrian', name: 'De Stijl', need: { jewels: 30 }, glass: ['#d8342c', '#2455a8', '#f2c230', '#f3efe4', '#d8342c', '#f2c230'],
    clear: '#d8d5cb', lead: '#0d0d0d', leadHi: '#3c3c3c', frame: '#101010', light: '#ffffff' },
  { id: 'midnight', name: 'Midnight', need: { windows: 60 }, glass: ['#3237a0', '#7447c4', '#25b6cc', '#c43ca8', '#1d5cc0', '#98a7d6'],
    clear: '#6d7896', lead: '#0b0b12', leadHi: '#43465e', frame: '#15151f', light: '#dfe8ff' },
];

export const SPARK = {
  ember: { core: '#fff6dc', glow: '#ffae3d' },
  flint: { core: '#ffffff', glow: '#9fd4ff' },
  ingot: { core: '#ffe2b8', glow: '#ff5f2e' },
  drifter: { core: '#f0fff8', glow: '#57f0c0' },
};

export const ICON = {
  shards: [
    { colour: 2, tone: 0, pts: [31.8, 199.6, 32.1, 198.7, 44.4, 166.7, 44.4, 166.6, 93, 180, 344, 379.4, 344, 493.4] },
    { colour: 5, tone: 0, pts: [54.2, 220.7, 344, 493.4, 344, 503.5, 168, 461.2] },
    { colour: 1, tone: 1, pts: [16, 584, 16, 424.7, 185.5, 465.4, 128.8, 584] },
    { colour: 3, tone: 1, pts: [16, 424.7, 16, 300.1, 17.8, 265.8, 23.2, 231.9, 31.8, 199.6, 54.2, 220.7, 168, 461.2] },
    { colour: 4, tone: 0, pts: [185.5, 465.4, 344, 503.5, 344, 584, 128.8, 584] },
    { colour: -1, tone: 0, pts: [93, 180, 339.3, 247.5, 342.2, 265.8, 344, 300.1, 344, 379.4] },
    { colour: 0, tone: 0, pts: [44.4, 166.6, 59.9, 136.1, 78.6, 107.3, 100.3, 80.6, 124.5, 56.3, 151.2, 34.7, 180, 16, 208.8, 34.7, 234.8, 55.8, 152.6, 196.3] },
    { colour: 1, tone: 1, pts: [234.8, 55.8, 235.5, 56.3, 259.8, 80.6, 281.4, 107.3, 300.1, 136.1, 315.6, 166.7, 328, 198.7, 336.8, 231.9, 339.3, 247.5, 152.6, 196.3] },
  ],
  spark: [292.5, 274.6],
};

export const SCENE = {
  glass: [
    { colour: 1, tone: 1, pts: [132.2, 427.5, 139.9, 419.3, 344, 573.3, 344, 584, 158.5, 584] },
    { colour: 2, tone: 1, pts: [139.9, 419.3, 261.6, 291.2, 297, 323.8, 257.4, 507.9] },
    { colour: 4, tone: 1, pts: [297, 323.8, 344, 367.1, 344, 573.3, 257.4, 507.9] },
    { colour: 5, tone: 1, pts: [16, 584, 16, 549.7, 132.2, 427.5, 158.5, 584] },
    { colour: 0, tone: 1, pts: [16, 549.7, 16, 435.9, 54.5, 381.8, 182.8, 374.2] },
    { colour: 3, tone: 1, pts: [16, 368.6, 16, 300.1, 17.8, 265.8, 23.2, 231.9, 32.1, 198.7, 44.4, 166.7, 59.9, 136.1, 72.3, 117, 130.8, 170.8] },
    { colour: 1, tone: 0, pts: [16, 435.9, 16, 368.6, 130.8, 170.8, 175.3, 211.8] },
    { colour: 4, tone: 1, pts: [54.5, 381.8, 129.1, 276.8, 204.7, 351.1, 182.8, 374.2] },
    { colour: 5, tone: 1, pts: [129.1, 276.8, 175.3, 211.8, 261.6, 291.2, 204.7, 351.1] },
  ],
  // the half the sparks stay in, and the half the cut seals
  clear: [283.9, 111.2, 300.1, 136.1, 315.6, 166.7, 328, 198.7, 336.8, 231.9, 342.2, 265.8, 344, 300.1, 344, 367.1, 164.9, 202.2],
  flood: { colour: 0, tone: 1, pts: [72.3, 117, 78.6, 107.3, 100.3, 80.6, 124.5, 56.3, 151.2, 34.7, 180, 16, 208.8, 34.7, 235.5, 56.3, 259.8, 80.6, 281.4, 107.3, 283.9, 111.2, 164.9, 202.2] },
  // where the cut starts, where each arm lands, and the longer arm's length
  line: { o: [219.8, 160.2], a: [283.9, 111.2], b: [164.9, 202.2], len: 80.7 },
  sparks: [
    { kind: 'ember', x: 269.6, y: 246.2, r: 6, drift: 18 },
    { kind: 'flint', x: 317.4, y: 281.8, r: 4.5, drift: 15.2 },
    { kind: 'drifter', x: 277.4, y: 158.7, r: 6, drift: 18 },
  ],
  fill: 72.9,   // per cent of the pane coloured before the cut
};
