/* Writes Floehelm's artwork data from the game itself.

     node --experimental-strip-types scripts/floehelm-art.mjs [path/to/FloehelmRN]

   The bay is FloehelmRN's own staged store-screenshot moment (bay 7, Quiet
   Reach III: tools/stage-screenshots.mjs plays it with the game's stepGame and
   the crosswind-dodging pilot), so the channels, stone islands, boats and the
   crosswind band are a state the game really produced. Colours, the boat hull
   and the harbor are the ones FloehelmRN/src/game/Scene.tsx draws with; the
   cells are merged into a few SVG paths so the page stays light.

   Outputs src/components/art/floehelmData.js. The build does not run this: it
   needs a FloehelmRN checkout, which CI has not got, so the output is
   committed. */

import { writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const game = resolve(process.argv[2] ?? join(root, '..', 'Floehelm', 'FloehelmRN'));
const load = (rel) => import(pathToFileURL(join(game, rel)).href);

const { COLS, ROWS, CELL, HARBOR, region, regionName, crosswindHalfWidth } = await load('src/core/game.ts');
const { stage } = await load('tools/stage-screenshots.mjs');

const g = stage('deep').run;
const at = (x, y) => (x < 0 || y < 0 || x >= COLS || y >= ROWS ? 9 : g.grid[y * COLS + x]);
const r1 = (v) => Math.round(v * 10) / 10;

// Ice as one path of horizontal runs; the darker lip where ice meets water
// below it; the bright edge where water lies above; heavy-ice cracks and the
// scattered surface marks — each the same rule Scene.tsx draws per cell.
let ice = '', lip = '', rim = '', cracks = '', marks = '';
const stone = [];
for (let y = 0; y < ROWS; y++) {
  for (let x = 0; x < COLS; ) {
    const t = at(x, y);
    if (t === 1 || t === 2) {
      let e = x;
      while (e < COLS && (at(e, y) === 1 || at(e, y) === 2)) e++;
      ice += `M${x * CELL} ${y * CELL}h${(e - x) * CELL}v${CELL}h${-(e - x) * CELL}Z`;
      x = e;
    } else x++;
  }
  for (let x = 0; x < COLS; x++) {
    const t = at(x, y), px = x * CELL, py = y * CELL;
    if (t === 9) {
      if (x > 0 && y > 0 && x < COLS - 1 && y < ROWS - 1) stone.push([x, y]);
      continue;
    }
    if (t === 0) continue;
    if (at(x, y + 1) === 0) lip += `M${px} ${py + CELL}h${CELL}v4h${-CELL}Z`;
    if (y > 0 && at(x, y - 1) === 0) rim += `M${px} ${py}h${CELL}`;
    if (t === 2) cracks += `M${px + 2} ${py + 10}L${px + 9} ${py + 5}L${px + 13} ${py + 7}`;
    else if ((x * 7 + y * 3) % 13 === 0) marks += `M${px + 3} ${py + 5}L${px + 7} ${py + 4}`;
  }
}

// The dotted way home of each sailing boat, down the distance field.
const routes = [];
for (const b of g.boats.filter((b) => b.state === 'sailing')) {
  let i = Math.floor(b.y) * COLS + Math.floor(b.x);
  for (let n = 0; n < 90; n++) {
    if (g.distance[i] <= 0) break;
    if (n % 2 === 0) routes.push([r1(((i % COLS) + 0.5) * CELL), r1((Math.floor(i / COLS) + 0.5) * CELL)]);
    let next = i, best = g.distance[i];
    for (const j of [i - 1, i + 1, i - COLS, i + COLS])
      if (j >= 0 && j < g.distance.length && g.distance[j] >= 0 && g.distance[j] < best) { best = g.distance[j]; next = j; }
    if (next === i) break;
    i = next;
  }
}

const colours = region(g.bay);
const data = {
  name: regionName(g.bay),
  bay: g.bay + 1,
  cols: COLS,
  rows: ROWS,
  cell: CELL,
  water: colours.water,
  ice: colours.ice,
  edge: colours.edge,
  paths: { ice, lip, rim, cracks, marks },
  stone,
  routes,
  boats: g.boats
    .filter((b) => b.state !== 'home')
    .map((b) => ({ x: r1(b.x * CELL), y: r1(b.y * CELL), deg: Math.round((b.angle * 180) / Math.PI + 90), kind: b.kind, state: b.state })),
  ship: { x: r1(g.player.x * CELL), y: r1(g.player.y * CELL), deg: Math.round((g.player.angle * 180) / Math.PI + 90) },
  harbor: { x: HARBOR.x * CELL, y: HARBOR.y * CELL },
  crosswind: g.hazardPhase >= 0 ? { x: g.hazardX * CELL, half: r1(crosswindHalfWidth(g.bay) * CELL), active: g.hazardPhase >= 2 } : null,
  delivered: g.delivered,
  quota: g.quota,
};

const out = `/* Generated by scripts/floehelm-art.mjs from FloehelmRN — do not edit.
   Bay ${data.bay}, ${data.name}: ${data.delivered} of ${data.quota} boats home. */
export const BAY = ${JSON.stringify(data)};
`;
await writeFile(join(root, 'src/components/art/floehelmData.js'), out);
console.log(`floehelmData.js: bay ${data.bay} ${data.name}, ${data.boats.length} boats, ${stone.length} stone cells, ${out.length} bytes`);
